project:
  type: website

website:
  title: "Developer portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: images/Heleen-Br√ºggen.pdf
        text: Curriculum Vitae
      - projects.qmd
      - text: Contact
        menu: 
          - text: Github
            href: https://github.com/heleenbrueggen
          - text: LinkedIn
            href: https://www.linkedin.com/in/heleenbrueggen/
          - text: Instagram
            href: https://www.instagram.com/heleenbrueggen/  

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 800px
      margin-width: 300px
      gutter-width: 1.5rem



